# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "e2-graphql-unions"
client_id = "575e281333f90e8e62da7f973ebd2413"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "nick-wesselman-dev.myshopify.com"
