# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "e5-function-performance"
client_id = "05294fbd27ec3055998fb249a7985e93"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "nick-wesselman-dev.myshopify.com"
